on:
  release:
    types:
      [
        created
      ]
  workflow_dispatch:

name: Deploy Prod

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Serverless
        run:
          |
          export SERVERLESS_ACCESS_KEY="$AWS_ACCESS_KEY_ID"

      - name: Install Dependencies
        run: |
          rm -f package-lock.json
          yarn install --frozen-lockfile
          
      - name: Deploy
        run: yarn deploy-prod
