on:
  push:
    branches:
      [
        main
      ]
  workflow_dispatch:

name: Deploy Staging

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Serverless
        run:
          |
          export SERVERLESS_ACCESS_KEY="$SERVERLESS_ACCESS_KEY"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
          
      - name: Deploy
        run: yarn deploy-staging
