on:
  pull_request:
    branches: [main]

name: Run Tests

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ~/ChumsApp

      - name: Checkout Tests
        uses: actions/checkout@v2
        with:
          repository: LiveChurchSolutions/ChumsTests
          path: ~/ChumsTests

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
    
      - name: Fetch Submodules
        run: 
          git submodule init && git submodule update
          working-directory: ~/ChumsApp

      - name: Install Dependencies
        run: 
          npm install
          working-directory: ~/ChumsApp
  
      - name: Install Test Project
        run: 
          npm install
          working-directory: ~/ChumsTests

      - name: Run Tests
        run:
          npm test
          working-directory: ~/ChumsTests
