on:
  pull_request:
    branches: [main]

name: Run Tests

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ~/ChumsApp

      - name: Checkout Tests
        uses: actions/checkout@v2
        with:
          repository: LiveChurchSolutions/ChumsTests
          path: ~/ChumsTests

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
    
      - name: Fetch Submodules
        working-directory: ~/ChumsApp
        run: git submodule init && git submodule update
          
      - name: Install Dependencies
        working-directory: ~/ChumsApp
        run: npm install

      - name: Copy .env
        working-directory: ~/ChumsApp
        run: cp dotenv.sample.txt .env

      - name: Start Server
        run: npm start
  
      - name: Install Test Project
        working-directory: ~/ChumsTests
        run: npm install
          
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ~/ChumsTests
          wait-on: 'http://localhost:3101'
          spec: |
            cypress/integration/*.spec.js
        env:
          CYPRESS_ACCESS_API: https://accessapi.staging.churchapps.org
          CYPRESS_ATTENDANCE_API: https://attendanceapi.staging.churchapps.org
          CYPRESS_GIVING_API: https://givingapi.staging.churchapps.org
          CYPRESS_MEMBERSHIP_API: https://membershipapi.staging.churchapps.org
          CYPRESS_appName: CHUMS
          CYPRESS_email: cypress.test@chums.org
          CYPRESS_password: password